# Generated by Django 3.0.8 on 2020-11-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubjectModel',
            new_name='Subjects',
        ),
    ]
