# Generated by Django 3.0.8 on 2020-11-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20201106_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
