# Generated by Django 3.0.8 on 2020-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_semester',
            field=models.IntegerField(default=0),
        ),
    ]
